# Generated by Django 4.2.4 on 2023-08-16 10:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mailing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mailing_datetime', models.DateTimeField(auto_now_add=True, verbose_name='Время и дата рассылки')),
                ('once', models.BooleanField(default=True, verbose_name='Единоразовая рассылка')),
                ('once_week', models.BooleanField(default=False, verbose_name='Рассылка раз в неделю')),
                ('once_month', models.BooleanField(default=False, verbose_name='Рассылка раз в месяц')),
                ('status', models.BooleanField(default=True, verbose_name='Статус рассылки')),
            ],
        ),
        migrations.CreateModel(
            name='Mail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_mail', models.CharField(max_length=50, verbose_name='тема письма')),
                ('body_mail', models.TextField(verbose_name='тело письма')),
                ('mailing', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='mailing.mailing')),
            ],
            options={
                'verbose_name': 'Письмо',
                'verbose_name_plural': 'Письмо',
            },
        ),
    ]
