# Generated by Django 4.2.4 on 2023-08-17 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0003_alter_mail_mailing'),
    ]

    operations = [
        migrations.AddField(
            model_name='mailing',
            name='count_mail',
            field=models.IntegerField(default=0, verbose_name='Количество рассылок'),
        ),
    ]
