# Generated by Django 4.2.4 on 2023-08-20 16:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mailing', '0004_mailing_count_mail'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mailing',
            options={'verbose_name': 'рассылка', 'verbose_name_plural': 'рассылки'},
        ),
        migrations.RemoveField(
            model_name='mail',
            name='mailing',
        ),
        migrations.RemoveField(
            model_name='mailing',
            name='count_mail',
        ),
        migrations.RemoveField(
            model_name='mailing',
            name='once',
        ),
        migrations.RemoveField(
            model_name='mailing',
            name='once_month',
        ),
        migrations.RemoveField(
            model_name='mailing',
            name='once_week',
        ),
        migrations.RemoveField(
            model_name='mailing',
            name='status',
        ),
        migrations.AddField(
            model_name='mailing',
            name='creator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='mailing',
            name='mail_status',
            field=models.CharField(choices=[('created', 'Создана'), ('started', 'Запущена'), ('done', 'Завершена')], default='created', max_length=20),
        ),
        migrations.AddField(
            model_name='mailing',
            name='message',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mailing.mail'),
        ),
        migrations.AddField(
            model_name='mailing',
            name='period',
            field=models.CharField(choices=[('daily', 'Ежедневная'), ('weekly', 'Раз в неделю'), ('monthly', 'Раз в месяц')], default='daily', max_length=20),
        ),
        migrations.AlterField(
            model_name='mailing',
            name='mailing_datetime',
            field=models.TimeField(verbose_name='Время рассылки'),
        ),
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_attempt', models.DateTimeField(verbose_name='Дата попытки')),
                ('status', models.CharField(max_length=150, verbose_name='Статус попытки')),
                ('answer', models.TextField(blank=True, null=True, verbose_name='ответ сервера')),
                ('mailing', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mailing.mailing')),
            ],
            options={
                'verbose_name': 'Лог',
                'verbose_name_plural': 'Логи',
            },
        ),
    ]
