# Generated by Django 4.2.3 on 2023-08-27 13:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mailing', '0005_alter_mailing_options_remove_mail_mailing_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailing',
            name='creator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Автор'),
        ),
        migrations.AlterField(
            model_name='mailing',
            name='mailing_datetime',
            field=models.TimeField(verbose_name='Время'),
        ),
        migrations.AlterField(
            model_name='mailing',
            name='message',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mailing.mail', verbose_name='Рассылка'),
        ),
        migrations.AlterField(
            model_name='mailing',
            name='period',
            field=models.CharField(choices=[('daily', 'Ежедневная'), ('weekly', 'Раз в неделю'), ('monthly', 'Раз в месяц')], default='daily', max_length=20, verbose_name='Периодичность'),
        ),
    ]
