# Generated by Django 4.2.3 on 2023-08-28 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0006_alter_mailing_creator_alter_mailing_mailing_datetime_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mailing',
            old_name='creator',
            new_name='user',
        ),
    ]
