# Generated by Django 4.2.3 on 2023-08-28 16:06

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0007_rename_creator_mailing_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailing',
            name='mailing_datetime',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Время'),
        ),
    ]
